# Site settings
title: Software Developer
email: f/xjkgpjvk"
url: https://github.com/Gabe1720/gabe1720.github.io
description: "My name is Gabe Hardy-Fowler and I am a senior Game Design and Computer Science
          major at Miami University. I have great passion for developing software, whether video games,
          websites, or others. With my dual major background, I've been fortunate
          enough to exercise my creativity while also being able to hone my technical skills and understanding
          across many tools, applications, and disciplines.
          
          Throughout my education and internship experience, I have not only gained experience and appreciation
          for software development, but cybersecurity and cloud technology as well. I am always excited by
          the prospect of learning something new, especially within the realm of technology, and I aim to
          be a life long learner. Whether working alongside a team or developing something on my own,
          there is no greater reward than becoming a better version of myself by the end of each project."
keywords: "your keywords, separated by commas"
skills: "Game Developer - Web Developer - Programmer"
meta_author: Hardy-Fowler Gabe

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1817 Bliss Ave
  - line: Findlay, OH 45840

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  entity_output: as_char
  toc_levels: 1..6
  parse_block_html: true
  smart_quotes: lsquo,rsquo,ldquo,rdquo
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
